### ISSUE TITLE
Unable to get Chat callback working

### ISSUE THREAD

**Issue by LK-Simon** [horazont/python3-openttd#2]
This may be my own lack of Python experience showing here (I honestly don't use Python often at all) but...

To your example code, on line 80, I add the following

`
    client.subscribe_callback_to_push(
        openttd.admin.UpdateType.CHAT,
        handle_chat)
`

The callback method is super simple, like the ones in your example:

`
def handle_chat(info):
    print(info)
`

However, I connect it up to my server's Admin port (all good there) but when a message is sent in-game, this happens in the Python console output:

ERROR:openttd.admin:task <Task finished name='Task-3' coro=<Client._update_task_impl() done, defined at /Users/simonstuart/DevProjects/OpenTTD-Discord-Bot/.venv/lib/python3.9/site-packages/openttd/admin.py:604> exception=TypeError("**<lambda>() missing 4 required positional arguments: 'action', 'desttype', 'dest', and 'msg'**") created at /Users/simonstuart/DevProjects/OpenTTD-Discord-Bot/.venv/lib/python3.9/site-packages/openttd/admin.py:587> unexpectedly exited: TypeError: <lambda>() missing 4 required positional arguments: 'action', 'desttype', 'dest', and 'msg'

Scratching my head on this one!

Please note I had to make some changes to make the code work in Python 3.9... I'll contribute my changes once I've got my implementation testing successfully. Python 3.9 deprecates a lot of the asyncio stuff your code uses.

**Comment by horazont** [comment]
Hi @LK-Simon,

It's a bit hard to figure this out without seeing your version of the code. Could you maybe push it to a fork or so so that I can take a look?

Mind that I haven't used this thing in years, so it is also possible that it won't work with current OpenTTD versions out of the box.
